main: io.th0rgal.oraxen.OraxenPlugin
name: Oraxen
version: ${projectVersion}
author: Th0rgal
api-version: "1.16"
softdepend: [ ProtocolLib, PlaceholderAPI, MythicMobs, MMOItems, CrateReloaded,
              BossShopPro, ItemBridge, WorldGuard, Towny, Factions, Lands, LightAPI ]
loadbefore: [ Realistic_World ]
