Plugin:
  name: "Oraxen"
  prefix: "&8&l[&bOraxen&8&l] ยง7"

Pack:
  generate: true
  upload: true
  send: true

  compression: BEST_COMPRESSION # see Deflater.class
  comment: "The content of this texture pack
   \nbelongs to the owner of the Oraxen
   \nplugin and any complete or partial
   \nuse must comply with the terms and
   \nconditions of Oraxen."