settings_version: 0.0.0

Plugin:
  name: "Oraxen"
  prefix: "&8&l[&bOraxen&8&l] §7"

Pack:
  # Nice for production servers, automatically set model ID in settings so
  # that you can other items without destroying the others already created
  automatically_set_model_id: false
  generation:
    generate: true
    compression: BEST_COMPRESSION # see Deflater.class
    comment: "The content of this texture pack
     \nbelongs to the owner of the Oraxen
     \nplugin and any complete or partial
     \nuse must comply with the terms and
     \nconditions of Oraxen."

  upload:
    enabled: true

  dispatch:
    send_pack: false
    send_pack_menu: true
    menu_json: "{\"extra\":[{\"clickEvent\":{\"action\":\"run_command\",\"value\":\"/oraxen pack getpack\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":[{\"text\":\"\u0026cClick here to load directly the resourcepack from the game\"}]},\"text\":\"\u0026c\u0026l\u0026nCLICK HERE\"},{\"text\":\"\n\u00267To download it from the internet, \"},{\"clickEvent\":{\"action\":\"open_url\",\"value\":\"http://transfer.sh/get/q6PTq/pack.zip\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":[{\"text\":\"\u0026aClick here to download the resourcepack from the website\"}]},\"text\":\"\u0026r\u0026a\u0026l\u0026nCLICK HERE\"}],\"text\":\"\n\u00268\u0026m\u0026l                         \u00268\u0026l{ \u0026bORΛXEN\u00268\u0026l }\u0026m                         \n\u00267This server is using a custom resourcepack to create new \u00267items. You can use your own pack in addition to server one.\n\n\u00267To try to load it directly from the game, \"}"